'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const script=fs.readFileSync(path.join(__dirname,'InventoryProbe.js'),'utf8');
let assertions=0;const check=(condition,message)=>{assert.ok(condition,message);assertions++;};
function fixture(){let visible=false,listener,callback;
 const slot=(n,count,weight,at=10)=>({slot:at,name:n,label:n==='salmon'?'サケ':n,count,weight,metadata:{quality:3}});
 const state={inventory:{leftInventory:{id:77,type:'player',slots:40,maxWeight:150000,items:[slot('salmon',2,400)]},rightInventory:{id:'truck-a',type:'trunk',label:'Truck A',slots:60,maxWeight:200000,items:[slot('salmon',10,2000)]}}};
 const store={getState:()=>state,subscribe:cb=>(callback=cb,()=>{})};
 const window={addEventListener:(type,cb)=>listener=cb,removeEventListener:()=>{}};
 const ctx=vm.createContext({window,performance:{now:()=>Date.now()},findStore:()=>store,inventoryVisible:()=>visible});
 const sample=()=>JSON.parse(window.__fpInventory060.sample());const send=data=>listener({data});
 vm.runInContext(script,ctx);
 return {slot,state,sample,send,show:()=>{visible=true;},hide:()=>{visible=false;},notify:()=>callback&&callback(),ctx};
}
const f=fixture();let s=f.sample();check(s.left.weight===400&&s.left.items[0].count===2,'initial whole-slot weight is not multiplied twice');
f.send({action:'refreshSlots',data:{items:[{inventory:77,item:f.slot('salmon',3,600)}]}});s=f.sample();check(s.left.weight===600&&s.left.items[0].count===3&&!s.open,'closed inventory catch updates weight and count');
check(s.source==='refreshSlots','message source exposed');
f.send({action:'refreshSlots',data:{items:[{inventory:77,item:f.slot('salmon',3,600)}]}});check(f.sample().left.items[0].count===3,'duplicate delivery is replacement, not addition');
f.show();check(f.sample().left.weight===600,'old visible Redux reference does not replace a newer message');
f.send({action:'refreshSlots',data:{items:[{inventory:77,item:{slot:10}},{inventory:'truck-a',item:f.slot('salmon',13,2600)}]}});s=f.sample();check(s.left.weight===0&&s.left.items.length===0&&s.right.items[0].count===13,'manual paired transfer replaces both inventories');
f.hide();check(f.sample().right.weight===2600,'closed trunk retains last confirmed snapshot');
f.send({action:'setupInventory',data:{rightInventory:{id:'truck-b',type:'trunk',slots:40,maxWeight:10000,items:[f.slot('salmon',1,200)]}}});s=f.sample();check(s.right.id==='truck-b'&&s.right.items[0].count===1&&s.left.items.length===0,'right-only setup switches truck without overwriting player');
f.send({action:'refreshSlots',data:{items:[{inventory:'truck-a',item:f.slot('salmon',999,999)}]}});check(f.sample().right.items[0].count===1,'another trunk does not contaminate active container');
f.send({action:'refreshSlots',data:{items:[{inventory:'player',item:f.slot('salmon',1,200,8)},{inventory:'player',item:f.slot('salmon',2,400,9)}]}});s=f.sample();check(s.left.weight===600&&s.left.items.length===2,'same fish across multiple slots retains full contents');
f.send({action:'refreshSlots',data:{items:{a:{inventory:77,item:{slot:8,name:'salmon',count:0}}}}});check(f.sample().left.items.length===1,'zero counts remove the slot');
f.send({action:'refreshSlots',data:{items:[{inventory:77,item:{slot:9,name:'salmon',count:2}}]}});check(f.sample().left.weight===-1&&!f.sample().left.weightsKnown,'missing weight is unknown, not zero or invented');
f.send({action:'setupInventory',data:{leftInventory:{id:77,type:'player',slots:40,maxWeight:150000,items:{9:f.slot('salmon',5,1000,9)}}}});s=f.sample();check(s.left.weight===1000&&s.left.items[0].count===5,'full resync supports slot dictionaries');
f.send({action:'refreshSlots',data:{items:[{inventory:77,item:{slot:9,name:'salmon',count:'bad',weight:0}}]}});s=f.sample();check(s.unknownDelta&&s.left.items[0].count===5,'malformed update requires resync without fake removal');
f.send({action:'setupInventory',data:{leftInventory:{id:77,type:'player',slots:40,maxWeight:150000,items:[]}}});check(!f.sample().unknownDelta&&f.sample().left.weight===0,'known-empty baseline clears sync error');
f.send({action:'init',data:{items:{lobster:{label:'ロブスター'}}}});f.send({action:'refreshSlots',data:{items:[{item:{name:'lobster',count:1,slot:11,weight:0.4,metadata:{b:2,a:1}}}]}});s=f.sample();check(s.left.items[0].label==='ロブスター','item catalog provides exact price-chart labels');check(s.left.items[0].meta==='{"a":1,"b":2}','canonical metadata matches existing receipt model');check(s.left.weight===0,'fractional grams sum and round once');
const g=fixture();g.show();g.state.inventory.leftInventory={...g.state.inventory.leftInventory,items:[g.slot('salmon',8,1600)]};g.notify();check(g.sample().left.weight===1600,'new visible Redux state reconciles server rollback');
const source=fs.readFileSync(path.join(__dirname,'BridgeRead.cs'),'utf8');check(source.includes('InventoryProbe.js')&&source.includes('window.__fpInventory060.sample()'),'production bridge loads tested message observer');
check(!script.includes('fetch(')&&!script.includes('.dispatch('),'inventory observer has no write callbacks');
const prices=JSON.parse(fs.readFileSync(path.join(__dirname,'fish-prices.json'),'utf8'));check(prices.length===41&&new Set(prices.map(x=>x.Label)).size===41,'price chart has 41 unique entries');check(prices.find(x=>x.Label==='ホワイトシーバス').Yen===500000,'repeated illustration is not a second price entry');
const result={pass:true,assertions,scope:'read-only NUI protocol fixtures, not a real FiveM server',cases:['closed catch','duplicate','paired manual transfer','trunk switch','unknown weights','slot dictionaries','bad update','catalog labels','rollback','chart']};
const out=process.argv[2];if(out){fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(result,null,2));}console.log(JSON.stringify(result,null,2));
