using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;
namespace FishingPilot {
 public static class Tests060 {
  static Inventory InventoryOf(int salmon,int unknown=0,int slot=10){var rows=new List<string>();if(salmon>0)rows.Add(slot.ToString("D4")+".salmon.e30="+salmon);if(unknown>0)rows.Add("0011.unpriced.e30="+unknown);var inv=Inventory.Parse("SNAPSHOT "+(salmon*200)+" 150000 "+rows.Count+" 40 "+(rows.Count>0?String.Join(",",rows):"-"));inv.Labels["salmon"]="サケ";return inv;}
  public static int Run(string output){int count=0;Action<bool,string> check=(ok,text)=>{count++;if(!ok)throw new Exception("060: "+text);};string dir=Path.Combine(output,"060-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);
   try{
    var prices=new PriceCatalog(dir);check(prices.Entries.Length==41,"41 distinct chart prices");long unit;check(prices.TryPrice("salmon","サケ",out unit)&&unit==20000,"exact Japanese label");check(!prices.TryPrice("salmon","unknown",out unit),"internal names never guessed");
    var value=prices.Evaluate(InventoryOf(2,3));check(value.Total==40000&&value.UnknownKinds==1&&value.UnknownUnits==3,"unknown prices remain explicitly incomplete");check(prices.Evaluate(InventoryOf(2,0,2)).Total==40000,"valuation includes fish in hotbar, not only transferable slots");check(!prices.Evaluate(new Inventory()).Known,"unknown inventory is not valued as empty");
    var stats=new CatchStatistics(dir);var baseline=InventoryOf(2);stats.Observe(baseline,0);var session=new ValueSession(prices,stats.Caught);var panel=session.Update(new Telemetry{Known=true,Inventory=baseline,Trunk=InventoryOf(10),TrunkId="A",TrunkLabel="A",TrunkOpen=true,Epoch="server-a"},stats,new LivePanel());check(panel.SessionValue.Total==0&&panel.TrunkValue.Total==200000,"existing stock not earnings, whole truck valued");
    var caught=InventoryOf(5);stats.Credit(baseline,caught);panel=session.Update(new Telemetry{Known=true,Inventory=caught,Trunk=InventoryOf(10),TrunkId="A",TrunkOpen=true,Epoch="server-a"},stats,panel);check(panel.SessionValue.Total==60000&&panel.HeldValue.Total==100000,"only newly caught quantity credited");
    var empty=InventoryOf(0);stats.Observe(empty,2);panel=session.Update(new Telemetry{Known=true,Inventory=empty,Trunk=InventoryOf(15),TrunkId="A",TrunkOpen=true,Epoch="server-a"},stats,panel);check(panel.SessionValue.Total==60000&&panel.HeldValue.Total==0&&panel.TrunkValue.Total==300000,"manual storage never credits earnings twice");
    panel=session.Update(new Telemetry{Known=true,Inventory=empty,Trunk=InventoryOf(14),TrunkId="A",TrunkOpen=false,Epoch="server-a"},stats,panel);check(panel.TrunkValue.Total==280000&&!panel.TrunkOpen,"late confirmed transfer updates closed last-known value");
    panel=session.Update(new Telemetry{Known=true,Inventory=empty,Trunk=InventoryOf(1),TrunkId="B",TrunkOpen=true,Epoch="server-a"},stats,panel);check(panel.TrunkValue.Total==20000&&panel.TrunkId=="B","truck replacement not aggregate across vehicles");
    panel=session.Update(new Telemetry{Known=false,Epoch="server-a"},stats,panel);check(!panel.Fresh&&panel.TrunkKnown&&!panel.TrunkOpen,"read failure preserves values with stale marker");
    panel=session.Update(new Telemetry{Known=true,Inventory=empty,Epoch="server-b"},stats,panel);check(!panel.TrunkKnown,"server epoch clears truck cache");
    File.WriteAllText(Path.Combine(dir,"price-aliases.json"),"{\"server_fish_1\":\"サケ\"}");check(new PriceCatalog(dir).TryPrice("server_fish_1","unknown",out unit)&&unit==20000,"explicit aliases persisted");
    var options=new Options();UiCommands.Validate(options);check(!options.AutoNudge&&options.Overlay.Opacity==90,"movement opt-in and slight transparency defaults");
    var json=new JavaScriptSerializer();var fields=new Dictionary<string,object>{{"Overlay",json.DeserializeObject(json.Serialize(new OverlayOptions{Position="bottom-right",Opacity=75,ShowDiagnostics=true}))},{"ShowOverlay",true},{"AutoNudge",true},{"NudgeHoldMs",400}};
    var replacement=UiCommands.UpdateOverlay(options,fields);check(replacement.AutoNudge&&replacement.Overlay.Position=="bottom-right"&&replacement.Overlay.Opacity==75&&!options.AutoNudge,"live overlay settings copy-on-write");
    bool rejected=false;fields["NudgeHoldMs"]=9999;try{UiCommands.UpdateOverlay(options,fields);}catch(ArgumentException){rejected=true;}check(rejected,"unsafe movement duration rejected");
    var schedule=new NudgeSchedule();schedule.Reset(0);check(!schedule.Due(true,0)&&!schedule.Due(true,599999)&&schedule.Due(true,600000),"first movement after ten minutes");schedule.Attempted(600000);check(!schedule.Due(true,1199999)&&schedule.Due(true,1200000),"no catch-up burst");schedule.Due(false,1210000);check(!schedule.Due(true,1300000)&&!schedule.Due(true,1899999)&&schedule.Due(true,1900000),"toggle-on starts a fresh interval");
    check(Recovery060.QuietTimeout(10000,0,1000,true,true,true,false,false,false),"missed result recovers after stable idle");check(!Recovery060.QuietTimeout(10000,0,1000,true,false,true,false,false,false),"no recovery without fresh scene");check(!Recovery060.QuietTimeout(10000,0,1000,true,true,false,false,false,false),"stale inventory blocks retry");check(!Recovery060.QuietTimeout(10000,0,1000,true,true,true,true,false,false),"inventory UI blocks retry");check(!Recovery060.QuietTimeout(10000,0,1000,true,true,true,false,true,false),"additional ring blocks retry");check(!Recovery060.QuietTimeout(10000,0,1000,true,true,true,false,false,true),"progress blocks retry");check(!Recovery060.QuietTimeout(2000,0,1000,true,true,true,false,false,false),"brief inter-round pause never triggers retry");check(!Recovery060.QuietTimeout(89999,0,0,false,true,true,false,false,false)&&Recovery060.QuietTimeout(90000,0,0,false,true,true,false,false,false),"long unobserved cast recovery is conservative");
    var controller=new RoundController();controller.Reset();controller.Observe(new Ring{Valid=true,Key=4,Start=200,End=212,Pointer=195},0);check(controller.Observe(new Ring{Valid=true,Key=4,Start=200,End=212,Pointer=199},20,10)<0,"prediction never sends before actual green");check(controller.Observe(new Ring{Valid=true,Key=4,Start=200,End=212,Pointer=202},30,2)==4,"narrow zone uses reduced safe entry margin");
    foreach(double pointer in new[]{195d,198d,199d,199.5d,199.99d}){controller.Reset();controller.Observe(new Ring{Valid=true,Key=4,Start=200,End=212,Pointer=pointer-4},0);check(controller.Observe(new Ring{Valid=true,Key=4,Start=200,End=212,Pointer=pointer},20,50)<0,"latency lead cannot cross an unobserved entry boundary");}
    controller.Reset();controller.Observe(new Ring{Valid=true,Key=4,Start=200,End=212,Pointer=205},0);check(controller.Observe(new Ring{Valid=true,Key=4,Start=200,End=212,Pointer=211},20,10)<0,"trailing safety margin remains protected");
    controller.Reset();controller.Observe(new Ring{Valid=true,Key=4,Start=356,End=8,Pointer=355},0);check(controller.Observe(new Ring{Valid=true,Key=4,Start=356,End=8,Pointer=359},20,2)==4,"narrow zone crossing zero remains eligible");
    var reader=new RingReader(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"digit-templates.json"));using(var bitmap=new Bitmap(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"fixtures","ring-1-60.png"))){check(reader.ReadFast(bitmap).Valid&&reader.ReadFast(bitmap).Key==1,"radius tracker reads current frames not cached digits");}
    check(!CdpBridge.FishingConnection.Forward(0,300,CancellationToken.None,()=>true),"movement requires verified local console");
    NativeMovementTest(check);
    File.WriteAllText(Path.Combine(output,"060.txt"),"PASS\nassertions="+count+"\nprice chart, full trunk, manual transfers, unknown prices, live configuration, retry guards, native timed key release\nNo actual FiveM or physical movement test.\n");return count;
   }finally{Directory.Delete(dir,true);}
  }
  static void NativeMovementTest(Action<bool,string> check){using(var f=new Form{Text="FishingPilot movement fixture",KeyPreview=true,Width=300,Height=160}){int downs=0,ups=0;f.KeyDown+=(s,e)=>{if(e.KeyCode==Keys.W)downs++;};f.KeyUp+=(s,e)=>{if(e.KeyCode==Keys.W)ups++;};f.Show();f.Activate();Application.DoEvents();var wait=Stopwatch.StartNew();while(Native.GetForegroundWindow()!=f.Handle&&wait.ElapsedMilliseconds<2000){Application.DoEvents();Thread.Sleep(10);f.Activate();}uint pid;Native.GetWindowThreadProcessId(f.Handle,out pid);IntPtr h=f.Handle;var cancel=new CancellationTokenSource();var task=Task.Run(()=>Native.HoldForward(h,pid,500,cancel.Token,()=>true));var sw=Stopwatch.StartNew();while(!task.IsCompleted){Application.DoEvents();if(sw.ElapsedMilliseconds>100)cancel.Cancel();Thread.Sleep(2);}for(int i=0;i<20;i++){Application.DoEvents();Thread.Sleep(3);}check(task.Result&&downs==1&&ups==1,"held W releases once on cancellation");check((Native.GetAsyncKeyState(0x57)&0x8000)==0,"no stuck forward key");check(!Native.HoldForward(h,pid+1,300,CancellationToken.None,()=>true),"wrong PID denies forward");check(!Native.HoldForward(h,pid,300,CancellationToken.None,()=>false),"movement toggle off denies key-down");f.Close();cancel.Dispose();}}
 }
}
